import os

os.makedirs('papers/regulator-lattice', exist_ok=True)

tex = open('papers/regulator-lattice/gentry-regulator-lattice.tex','w',encoding='utf-8')
w = tex.write
w('\\\\documentclass[12pt]{article}\\n')
w('\\\\usepackage{amsmath,amssymb,amsfonts,amsthm,booktabs,hyperref,geometry,authblk}\\n')
w('\\\\geometry{margin=1in}\\n')
w('\\\\newtheorem{theorem}{Theorem}[section]\\n')
w('\\\\newtheorem{conjecture}[theorem]{Conjecture}\\n')
w('\\\\theoremstyle{definition}\\\\newtheorem{definition}[theorem]{Definition}\\n')
w('\\\\theoremstyle{remark}\\\\newtheorem{remark}[theorem]{Remark}\\n')
w('\\\\newcommand{\\\\R}{\\\\mathbb{R}}\\n')
w('\\\\newcommand{\\\\Q}{\\\\mathbb{Q}}\\n')
w('\\\\newcommand{\\\\OK}{\\\\mathcal{O}_K}\\n')
w('\\\\title{Regulator Lattices and the Geometry of Mass Hierarchies}\\n')
w('\\\\author[1]{Marvin L.\\\\ Gentry}\\n')
w('\\\\affil[1]{Independent Researcher\\\\\\\\\\n')
w('  \\\\texttt{drmlgentry@protonmail.com}\\\\\\\\\\n')
w('  ORCID: 0009-0006-4550-2663}\\n')
w('\\\\date{}\\n')
w('\\\\begin{document}\\n\\\\maketitle\\n')
w('\\\\begin{abstract}\\n')
w('We investigate the hypothesis that observed logarithmic fermion mass ratios\\n')
w('are approximated by points on the regulator lattice of a totally real number\\n')
w('field. The anisotropy ratio $\\\\kappa=\\\\lambda_{\\\\max}/\\\\lambda_{\\\\min}$ of the\\n')
w('Gram matrix is constrained by results of Dobrowolski, Zimmert, and Friedman.\\n')
w('We conjecture that $\\\\kappa$ is uniformly bounded for totally real fields of\\n')
w('fixed degree (Conjecture~\\\\ref{conj:kappa}). Computational evidence from nine\\n')
w('totally real cubic fields gives $\\\\kappa\\\\in[1.4,12.8]$, supporting the conjecture.\\n')
w('Four of nine fields exceed the spectrum obstruction threshold $\\\\kappa\\\\geq 5.74$\\n')
w('and are not ruled out by the obstruction alone; the additional requirement that\\n')
w('unit generator lengths match observed fermion mass ratios provides the decisive\\n')
w('further constraint.\\n')
w('\\\\end{abstract}\\n')
w('\\\\section{Introduction}\\n')
w('The nine charged Standard Model fermion masses span roughly thirteen orders of\\n')
w('magnitude. In logarithmic coordinates, approximate regularities suggest an\\n')
w('underlying arithmetic structure. A natural candidate is the regulator lattice\\n')
w('of a totally real number field: under the logarithmic embedding, the unit group\\n')
w('$\\\\OK^\\\\times$ becomes a lattice in a hyperplane of $\\\\R^r$~\\\\cite{neukirch}.\\n')
w('This paper studies geometric constraints that identifying fermion masses with\\n')
w('regulator lattice points would impose, using classical results of\\n')
w('Dobrowolski~\\\\cite{dobrowolski} and Zimmert--Friedman~\\\\cite{zimmert,friedman},\\n')
w('and connects to the spectrum obstruction of the companion paper~\\\\cite{paper7}.\\n')
w('\\\\section{Regulator Lattices}\\n')
w('Let $K$ be totally real of degree $r=[K:\\\\Q]$ with embeddings\\n')
w('$\\\\sigma_1,\\\\ldots,\\\\sigma_r\\\\colon K\\\\hookrightarrow\\\\R$.\\n')
w('The logarithmic embedding is\\n')
w('\\\\begin{equation}\\n')
w('\\\\Lambda(\\\\epsilon)=\\\\bigl(\\\\log|\\\\sigma_1(\\\\epsilon)|,\\\\ldots,\\\\log|\\\\sigma_r(\\\\epsilon)|\\\\bigr).\\n')
w('\\\\end{equation}\\n')
w('The image lies in $H=\\\\{x\\\\in\\\\R^r:x_1+\\\\cdots+x_r=0\\\\}$.\\n')
w("Dirichlet's unit theorem gives a rank-$(r-1)$ lattice with covolume $R_K$.\\n")
w('\\\\begin{definition}[Anisotropy ratio]\\n')
w('With fundamental unit log vectors $v_i=\\\\Lambda(\\\\epsilon_i)$, Gram matrix\\n')
w('$G_{ij}=\\\\langle v_i,v_j\\\\rangle$, and eigenvalues\\n')
w('$0<\\\\lambda_1\\\\leq\\\\cdots\\\\leq\\\\lambda_{r-1}$, the \\\\emph{anisotropy ratio} is\\n')
w('$\\\\kappa(K)=\\\\lambda_{r-1}/\\\\lambda_1$.\\n')
w('\\\\end{definition}\\n')
w('\\\\section{Classical Bounds}\\n')
w('\\\\begin{theorem}[Dobrowolski~\\\\cite{dobrowolski}]\\n')
w('For any non-torsion unit $\\\\epsilon$,\\n')
w('$\\\\|\\\\Lambda(\\\\epsilon)\\\\|\\\\geq\\\\delta_r>0$ uniformly in the degree.\\n')
w('\\\\end{theorem}\\n')
w('\\\\begin{theorem}[Zimmert--Friedman~\\\\cite{zimmert,friedman}]\\n')
w('For totally real $K$ of degree $r$,\\n')
w('$a_r(\\\\log|D_K|)^{r-1}\\\\leq R_K\\\\leq b_r(\\\\log|D_K|)^{r-1}$.\\n')
w('\\\\end{theorem}\\n')
w('\\\\section{The Bounded Anisotropy Conjecture}\\n')
w('\\\\begin{conjecture}[Bounded anisotropy]\\\\label{conj:kappa}\\n')
w('For fixed $r$, there exists $C_r$ such that $\\\\kappa(K)\\\\leq C_r$\\n')
w('for every totally real field $K$ of degree $r$.\\n')
w('\\\\end{conjecture}\\n')
w('The heuristic motivation: large $\\\\kappa$ forces $\\\\lambda_1$ small,\\n')
w('but Dobrowolski forbids arbitrarily short non-zero lattice vectors.\\n')
w('Closing this argument rigorously---showing a small Gram eigenvalue\\n')
w('forces a short lattice vector---is the main open problem.\\n')
w('\\\\section{Computational Evidence}\\n')
w('We surveyed nine totally real cubic fields by scanning integer combinations\\n')
w('$a+b\\\\alpha+c\\\\alpha^2$ with $|a|,|b|,|c|\\\\leq 6$ for units of norm $\\\\pm1$,\\n')
w('then computed $\\\\kappa$ from Gram matrix eigenvalues.\\n')
w('Code: \\\\texttt{code/kappa\\\\_cubic.py}.\\n')
w('\\\\begin{table}[h]\\\\centering\\n')
w('\\\\begin{tabular}{lrrrrr}\\\\toprule\\n')
w('Field & Units & $\\\\lambda_1$ & $\\\\lambda_2$ & $\\\\kappa$ & vs.\\\\ threshold \\\\\\\\\\n')
w('\\\\midrule\\n')
w('$x^3-3x+1$     & 17 & 2.548 &  7.644 &  3.000 & below \\\\\\\\\\n')
w('$x^3-x^2-2x+1$ & 28 & 6.513 & 10.302 &  1.582 & below \\\\\\\\\\n')
w('$x^3-4x+1$     & 13 & 2.279 & 29.211 & 12.817 & above \\\\\\\\\\n')
w('$x^3-x^2-3x+1$ & 19 & 7.257 & 10.281 &  1.417 & below \\\\\\\\\\n')
w('$x^3-5x+1$     & 12 & 3.581 & 27.089 &  7.564 & above \\\\\\\\\\n')
w('$x^3-2x^2-x+1$ & 32 & 5.880 & 14.088 &  2.396 & below \\\\\\\\\\n')
w('$x^3-6x+2$     &  6 & 4.636 & 20.965 &  4.523 & below \\\\\\\\\\n')
w('$x^3-x^2-4x+3$ & 14 & 2.172 & 21.544 &  9.921 & above \\\\\\\\\\n')
w('$x^3-3x^2-x+1$ & 19 & 1.685 & 19.675 & 11.673 & above \\\\\\\\\\n')
w('\\\\bottomrule\\n')
w('\\\\multicolumn{6}{l}{Threshold for $N\\\\leq 6$: $\\\\kappa\\\\geq 5.74$.}\\n')
w('\\\\end{tabular}\\n')
w('\\\\caption{Anisotropy ratios for nine totally real cubic fields.\\n')
w('$\\\\kappa\\\\in[1.4,12.8]$; four fields exceed the obstruction threshold.}\\n')
w('\\\\label{tab:kappa}\\\\end{table}\\n')
w('\\\\section{Connection to the Spectrum Obstruction}\\n')
w('The spectrum obstruction of~\\\\cite{paper7} requires condition number\\n')
w('$\\\\kappa\\\\geq 34.46/N$ for coordinate bound $N$; for $N\\\\leq 6$\\n')
w('this gives $\\\\kappa\\\\geq 5.74$. Four fields in Table~\\\\ref{tab:kappa}\\n')
w('exceed this threshold and are not ruled out by the obstruction alone.\\n')
w('The decisive further constraint is that unit generator lengths must\\n')
w('match observed fermion mass ratios. Numerical tests on the quartic\\n')
w('field $x^4-x^3-4x^2+4x+1$ showed unit log norms do not match required\\n')
w('generator lengths (see \\\\texttt{code/verify\\\\_ckm\\\\_v2.py}).\\n')
w('\\\\section{Open Problems}\\n')
w('\\\\begin{enumerate}\\n')
w('\\\\item Prove or disprove Conjecture~\\\\ref{conj:kappa} for $r=3$.\\n')
w('\\\\item Extend the survey to $r=4$: is $\\\\kappa$ bounded for quartic fields?\\n')
w('\\\\item Find a totally real field whose unit generator lengths match fermion mass ratios.\\n')
w('\\\\item Determine whether any totally real field satisfies both the anisotropy\\n')
w('threshold and the generator length constraints simultaneously.\\n')
w('\\\\end{enumerate}\\n')
w('\\\\section{Conclusion}\\n')
w('Computational evidence from nine cubic fields gives $\\\\kappa\\\\in[1.4,12.8]$,\\n')
w('supporting Conjecture~\\\\ref{conj:kappa}. Four fields exceed the spectrum\\n')
w('obstruction threshold; all are further constrained by the generator length\\n')
w('requirement. Finding a field satisfying both constraints simultaneously\\n')
w('is the central open problem.\\n')
w('\\\\bibliographystyle{plain}\\n')
w('\\\\bibliography{gentry-regulator-lattice}\\n')
w('\\\\end{document}\\n')
tex.close()
print('tex written')

bib = open('papers/regulator-lattice/gentry-regulator-lattice.bib','w',encoding='utf-8')
b = bib.write
b('@book{neukirch,\\n  author={J. Neukirch},\\n  title={Algebraic Number Theory},\\n  publisher={Springer},\\n  year={1999}}\\n')
b('@article{friedman,\\n  author={E. Friedman},\\n  title={Analytic formulas for the regulator of a number field},\\n  journal={Invent. Math.},\\n  volume={98},pages={599--622},year={1989}}\\n')
b('@article{zimmert,\\n  author={R. Zimmert},\\n  title={Ideale kleiner {N}orm in {I}dealklassen},\\n  journal={Invent. Math.},\\n  volume={62},pages={367--380},year={1981}}\\n')
b('@article{dobrowolski,\\n  author={E. Dobrowolski},\\n  title={On a question of {L}ehmer},\\n  journal={Acta Arith.},\\n  volume={34},pages={391--401},year={1979}}\\n')
b('@unpublished{paper7,\\n  author={M. L. Gentry},\\n  title={Uniqueness-First {EFT} Realization of Logarithmic Mass Lattices},\\n  note={Companion paper, this series}}\\n')
bib.close()
print('bib written')
