import os
path = r'C:\\dev\\framework\\papers\\regulator-lattice\\gentry-regulator-lattice.tex'
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, 'w', encoding='utf-8') as f:\n    def w(s): f.write(s + '\\n')
    w(r'\\documentclass[12pt]{article}')
    w(r'\\usepackage{amsmath,amssymb,amsfonts,amsthm,booktabs,hyperref,geometry,authblk}')
    w(r'\\geometry{margin=1in}')
    w(r'\\newtheorem{theorem}{Theorem}[section]')
    w(r'\\newtheorem{conjecture}[theorem]{Conjecture}')
    w(r'\\theoremstyle{definition}')
    w(r'\\newtheorem{definition}[theorem]{Definition}')
    w(r'\\theoremstyle{remark}')
    w(r'\\newtheorem{remark}[theorem]{Remark}')
    w(r'\\newcommand{\\R}{\\mathbb{R}}')
    w(r'\\newcommand{\\Q}{\\mathbb{Q}}')
    w(r'\\newcommand{\\OK}{\\mathcal{O}_K}')
    w(r'\\title{Regulator Lattices and the Geometry of Mass Hierarchies}')
    w(r'\\author[1]{Marvin L.\\ Gentry}')
    w(r'\\affil[1]{Independent Researcher\\\\')
    w(r'  \\texttt{drmlgentry@protonmail.com}\\\\')
    w(r'  ORCID: 0009-0006-4550-2663}')
    w(r'\\date{}')
    w(r'\\begin{document}')
    w(r'\\maketitle')
    w(r'')
    w(r'\\begin{abstract}')
    w(r'We investigate the hypothesis that observed logarithmic fermion mass ratios')
    w(r'are approximated by points on the regulator lattice of a totally real number')
    w(r'field. The anisotropy ratio $\\kappa=\\lambda_{\\max}/\\lambda_{\\min}$ of the')
    w(r'Gram matrix is constrained by results of Dobrowolski, Zimmert, and Friedman.')
    w(r'We conjecture that $\\kappa$ is uniformly bounded for totally real fields of')
    w(r'fixed degree (Conjecture~\\ref{conj:kappa}). Computational evidence from nine')
    w(r'totally real cubic fields gives $\\kappa\\in[1.4,12.8]$, supporting the')
    w(r'conjecture. Four fields exceed the spectrum obstruction threshold')
    w(r'$\\kappa\\geq 5.74$ and are not ruled out by the obstruction alone; generator')
    w(r'length matching provides the decisive further constraint.')
    w(r'\\end{abstract}')
    w(r'')
    w(r'\\section{Introduction}')
    w(r'The nine charged Standard Model fermion masses span roughly thirteen orders')
    w(r'of magnitude. In logarithmic coordinates, approximate regularities suggest')
    w(r'an underlying arithmetic structure. A natural candidate is the regulator')
    w(r'lattice of a totally real number field: under the logarithmic embedding, the')
    w(r'unit group $\\OK^\\times$ becomes a lattice in a hyperplane of $\\R^r$~\\cite{neukirch}.')
    w(r'This paper studies geometric constraints that identifying fermion masses with')
    w(r'regulator lattice points would impose, using results of')
    w(r'Dobrowolski~\\cite{dobrowolski} and Zimmert--Friedman~\\cite{zimmert,friedman},')
    w(r'and connects to the spectrum obstruction of the companion paper~\\cite{paper7}.')
    w(r'')
    w(r'\\section{Regulator Lattices}')
    w(r'Let $K$ be totally real of degree $r=[K:\\Q]$ with embeddings')
    w(r'$\\sigma_1,\\ldots,\\sigma_r\\colon K\\hookrightarrow\\R$.')
    w(r'The logarithmic embedding is')
    w(r'\\begin{equation}')
    w(r'\\Lambda(\\epsilon)=\\bigl(\\log|\\sigma_1(\\epsilon)|,\\ldots,\\log|\\sigma_r(\\epsilon)|\\bigr).')
    w(r'\\end{equation}')
    w(r'The image lies in $H=\\{x\\in\\R^r:x_1+\\cdots+x_r=0\\}$.')
    w(r"Dirichlet's unit theorem gives a rank-$(r-1)$ lattice with covolume $R_K$.")
    w(r'')
    w(r'\\begin{definition}[Anisotropy ratio]')
    w(r'With fundamental unit log vectors $v_i=\\Lambda(\\epsilon_i)$, Gram matrix')
    w(r'$G_{ij}=\\langle v_i,v_j\\rangle$, and eigenvalues')
    w(r'$0<\\lambda_1\\leq\\cdots\\leq\\lambda_{r-1}$, the \\emph{anisotropy ratio} is')
    w(r'$\\kappa(K)=\\lambda_{r-1}/\\lambda_1$.')
    w(r'\\end{definition}')
    w(r'')
    w(r'\\section{Classical Bounds}')
    w(r'')
    w(r'\\begin{theorem}[Dobrowolski~\\cite{dobrowolski}]')
    w(r'For any non-torsion unit $\\epsilon$,')
    w(r'$\\|\\Lambda(\\epsilon)\\|\\geq\\delta_r>0$ uniformly in the degree.')
    w(r'\\end{theorem}')
    w(r'')
    w(r'\\begin{theorem}[Zimmert--Friedman~\\cite{zimmert,friedman}]')
    w(r'For totally real $K$ of degree $r$,')
    w(r'$a_r(\\log|D_K|)^{r-1}\\leq R_K\\leq b_r(\\log|D_K|)^{r-1}$.')
    w(r'\\end{theorem}')
    w(r'')
    w(r'\\section{The Bounded Anisotropy Conjecture}')
    w(r'')
    w(r'\\begin{conjecture}[Bounded anisotropy]\\label{conj:kappa}')
    w(r'For fixed $r$, there exists $C_r$ such that $\\kappa(K)\\leq C_r$')
    w(r'for every totally real field $K$ of degree $r$.')
    w(r'\\end{conjecture}')
    w(r'')
    w(r'The heuristic motivation: large $\\kappa$ forces $\\lambda_1$ small,')
    w(r'but Dobrowolski forbids arbitrarily short non-zero lattice vectors.')
    w(r'Closing this argument rigorously is the main open problem.')
    w(r'')
    w(r'\\section{Computational Evidence}')
    w(r'We surveyed nine totally real cubic fields by scanning $a+b\\alpha+c\\alpha^2$')
    w(r'with $|a|,|b|,|c|\\leq 6$ for units of norm $\\pm1$, then computed $\\kappa$')
    w(r'from Gram matrix eigenvalues. Code: \\texttt{code/kappa\\_cubic.py}.')
    w(r'')
    w(r'\\begin{table}[h]')
    w(r'\\centering')
    w(r'\\begin{tabular}{lrrrrr}')
    w(r'\\toprule')
    w(r'Field & Units & $\\lambda_1$ & $\\lambda_2$ & $\\kappa$ & vs.\\ threshold \\\\')
    w(r'\\midrule')
    w(r'$x^3-3x+1$     & 17 & 2.548 &  7.644 &  3.000 & below \\\\')
    w(r'$x^3-x^2-2x+1$ & 28 & 6.513 & 10.302 &  1.582 & below \\\\')
    w(r'$x^3-4x+1$     & 13 & 2.279 & 29.211 & 12.817 & above \\\\')
    w(r'$x^3-x^2-3x+1$ & 19 & 7.257 & 10.281 &  1.417 & below \\\\')
    w(r'$x^3-5x+1$     & 12 & 3.581 & 27.089 &  7.564 & above \\\\')
    w(r'$x^3-2x^2-x+1$ & 32 & 5.880 & 14.088 &  2.396 & below \\\\')
    w(r'$x^3-6x+2$     &  6 & 4.636 & 20.965 &  4.523 & below \\\\')
    w(r'$x^3-x^2-4x+3$ & 14 & 2.172 & 21.544 &  9.921 & above \\\\')
    w(r'$x^3-3x^2-x+1$ & 19 & 1.685 & 19.675 & 11.673 & above \\\\')
    w(r'\\bottomrule')
    w(r'\\multicolumn{6}{l}{Threshold: $\\kappa\\geq 5.74$ for $N\\leq 6$.}')
    w(r'\\end{tabular}')
    w(r'\\caption{Anisotropy ratios for nine totally real cubic fields.')
    w(r'$\\kappa\\in[1.4,12.8]$; four exceed the obstruction threshold.}')
    w(r'\\label{tab:kappa}')
    w(r'\\end{table}')
    w(r'')
    w(r'\\section{Connection to the Spectrum Obstruction}')
    w(r'The spectrum obstruction of~\\cite{paper7} requires $\\kappa\\geq 34.46/N$;')
    w(r'for $N\\leq 6$ this gives $\\kappa\\geq 5.74$. Four fields in')
    w(r'Table~\\ref{tab:kappa} exceed this threshold and are not ruled out by the')
    w(r'obstruction alone. The decisive further constraint is that unit generator')
    w(r'lengths must match observed fermion mass ratios. Numerical tests on')
    w(r'$x^4-x^3-4x^2+4x+1$ showed unit log norms do not match required generator')
    w(r'lengths (see \\texttt{code/verify\\_ckm\\_v2.py}).')
    w(r'')
    w(r'\\section{Open Problems}')
    w(r'\\begin{enumerate}')
    w(r'\\item Prove or disprove Conjecture~\\ref{conj:kappa} for $r=3$.')
    w(r'\\item Extend the survey to $r=4$: is $\\kappa$ bounded for quartic fields?')
    w(r'\\item Find a totally real field whose unit generator lengths match fermion mass ratios.')
    w(r'\\item Determine whether any totally real field satisfies both constraints simultaneously.')
    w(r'\\end{enumerate}')
    w(r'')
    w(r'\\section{Conclusion}')
    w(r'Computational evidence from nine cubic fields gives $\\kappa\\in[1.4,12.8]$,')
    w(r'supporting Conjecture~\\ref{conj:kappa}. Four fields exceed the spectrum')
    w(r'obstruction threshold; all are further constrained by the generator length')
    w(r'requirement. Finding a field satisfying both constraints simultaneously')
    w(r'is the central open problem.')
    w(r'')
    w(r'\\bibliographystyle{plain}')
    w(r'\\bibliography{gentry-regulator-lattice}')
    w(r'')
    w(r'\\end{document}')

t = open(path, encoding='utf-8').read()
lines = t.splitlines()
print('total lines:', len(lines))
print('line 1:', repr(lines[0]))
print('line 2:', repr(lines[1]))
print('last:', repr(lines[-1]))
