#############################################################################
# bianchi_d7_lowindex.g
#
# PSL_2(O_{-7}) / PGL_2(O_{-7}) low-index subgroup search for m009/m010.
#
# SOURCE for the T7 = PSL_2(O_{-7}) presentation (read directly, full text,
# legitimately open access -- arxiv.org/pdf/2206.01262, no institutional
# access or piracy involved):
#   Tanner Reese, "Presentations for Singly-Cusped Bianchi Groups,"
#   arXiv:2206.01262 (2022); published version Topology Appl. 328 (2023),
#   article 108443, DOI 10.1016/j.topol.2023.108443 (confirmed via
#   Crossref metadata). Both correctly attributed solely to Tanner Reese --
#   an earlier relayed "Dinakaran (2022)" attribution for this arXiv id is
#   confirmed FALSE, no such paper exists.
#
# Page 12 of the paper gives, for d=-7 (omega = (1+sqrt(-7))/2, matching
# d=-7 = 1 mod 4):
#   A = [[1,1],[0,1]]   B = [[0,1],[-1,0]]   U = [[1,omega],[0,1]]
#   Gamma_{-7} = < A,B,U | B^2, (BA)^3, A U A^-1 U^-1, (B A U^-1 B U)^2 >
# matching the paper's own table (O_{-7} row: 3 generators, 4 relations,
# simplified via Magma). Gamma_{-7}^ab = C2 x C_infinity (paper's Table,
# Section 4) -- not independently re-derived here, recorded as a sanity
# check available for anyone re-running this.
#
# Gamma_infinity (translations, the cusp stabilizer) is generated by
# T_1 = A and T_omega = U directly (Section 2 of the paper: T_s is the
# matrix [[1,s],[0,1]]) -- so the peripheral generators below are simply
# A and U, not separately computed.
#
# Torsion: the relators B^2 and (BA)^3 show B has order 2 and BA has
# order 3 in PSL_2(O_{-7}); these are the elliptic conjugacy-class
# representatives used for the coset-action torsion test below. This is
# read directly off the presentation's own relators, not assumed from
# outside knowledge.
#
# STAGE 2 (B7 = PGL_2(O_{-7})): generated by T7 plus one projective
# involution J: z -> -z (matrix diag(-1,1), determinant -1, J^2=1 in
# PGL_2). Conjugation action computed by hand from the real matrices
# above AND independently checked numerically in Python (both agree,
# zero numerical error):
#   J A J^-1 = A^-1,   J B J^-1 = B^-1,   J U J^-1 = U^-1
# (all three generators are inverted by J -- makes geometric sense for A
# and U since they're translations and z->-z negates translations; for B
# it follows from the direct 2x2 matrix computation, verified both by
# hand and numerically).
#
# What's independently confirmed about the B7 = PGL_2(O_{-7}) target
# itself (computed directly in Sage, not from any relay):
#   class_number(Q(sqrt(-7))) = 1, unit group order 2
#   => [PGL_2(O_K):PSL_2(O_K)] = 2 by elementary algebra alone
#   => covol(B7) = covol(T7)/2 = 0.444457463908...
#   => 2.666744783449.../0.444457463908... = 6.000000... exactly
# What is NOT independently confirmed: that PGL_2(O_{-7}) is genuinely
# Vulakh's *maximal* discrete extension (not just *a* discrete
# extension) -- L. Ya. Vulakh, "Reflections in extended Bianchi groups,"
# Math. Proc. Cambridge Philos. Soc. 115(1), 1994, DOI
# 10.1017/S0305004100071887, is a real, correctly-attributed paper
# (confirmed via Cambridge's listing), but its full text has not been
# read, so treat B7=PGL_2(O_{-7}) as plausible/consistent, not proved
# from source.
#############################################################################

SetInfoLevel(InfoWarning, 1);

########################################################################
# 1. PRESENTATION (Reese, arXiv:2206.01262, p.12, d=-7 row)
########################################################################

F := FreeGroup("A", "B", "U");
gens := GeneratorsOfGroup(F);
A := gens[1];; B := gens[2];; U := gens[3];;

rels := [
    B^2,
    (B*A)^3,
    A*U*A^-1*U^-1,
    (B*A*U^-1*B*U)^2
];

T7 := F / rels;
tg := GeneratorsOfGroup(T7);
A7 := tg[1];; B7g := tg[2];; U7 := tg[3];;

Print("T7 presentation loaded (", Length(rels), " relators, Reese arXiv:2206.01262 p.12)\n");

########################################################################
# 2. PERIPHERAL SUBGROUP: Gamma_infinity = <T_1, T_omega> = <A, U>
########################################################################

p1 := A7;;  # T_1
p2 := U7;;  # T_omega

########################################################################
# 3. TORSION REPRESENTATIVES: B (order 2), B*A (order 3) -- read directly
# off the relators B^2 and (BA)^3 above.
########################################################################

torsionReps := [ B7g, B7g*A7 ];

########################################################################
# 4. LOW-INDEX ENUMERATION (Stage 1, ordinary T7 -- control run)
########################################################################

lis := LowIndexSubgroupsFpGroup(T7, 6);
Print("Number of conjugacy classes index <= 6: ", Length(lis), "\n");

idx3 := Filtered(lis, H -> Index(T7, H) = 3);
idx6 := Filtered(lis, H -> Index(T7, H) = 6);
Print("Index 3 classes: ", Length(idx3), "\n");
Print("Index 6 classes: ", Length(idx6), "\n");

########################################################################
# 5. COSET-ACTION TORSION TEST
#
# Deliberately uses the coset action rather than a generic
# IsTorsionFree(H) call, which is not reliable for an arbitrary
# finite-index subgroup of an infinite finitely presented group: t is
# conjugate into H iff its permutation on H\G has a fixed point.
########################################################################

IsTorsionFreeByCosetAction := function(G, H, tors)
    local cosets, act, t, pt;
    cosets := RightCosets(G, H);
    act := ActionHomomorphism(G, cosets, OnRight);
    for t in tors do
        for pt in [1 .. Length(cosets)] do
            if pt ^ Image(act, t) = pt then
                return false;
            fi;
        od;
    od;
    return true;
end;

########################################################################
# 6. CUSP COUNT FROM DOUBLE COSETS H\G/P
#
# #{cusps of H} = |H\G/P|; P-orbits on H\G give exactly the double
# cosets, more rigorous here than inferring cusp count from H_1.
########################################################################

NumberOfCusps := function(G, H, periphGens)
    local cosets, act, Pperm, orbs;
    cosets := RightCosets(G, H);
    act := ActionHomomorphism(G, cosets, OnRight);
    Pperm := Group(List(periphGens, g -> Image(act, g)));
    orbs := Orbits(Pperm, [1 .. Length(cosets)]);
    return Length(orbs);
end;

########################################################################
# 7. ABELIANIZATION
########################################################################

HomologyInvariants := function(H)
    local iso, HFp;
    iso := IsomorphismFpGroup(H);
    HFp := Image(iso);
    return AbelianInvariants(HFp);  # GAP: 0 marks an infinite cyclic factor
end;

########################################################################
# 8. STAGE 1 CONTROL: INDEX 3 -- expect torsion-free = false, every time
########################################################################

Print("\n=== INDEX 3 CONTROL (expect torsion-free=false for all) ===\n");
for H in idx3 do
    Print("index=3  torsion-free=", IsTorsionFreeByCosetAction(T7, H, torsionReps), "\n");
od;
# If GAP reports any index-3 class as torsion-free: STOP. That means the
# presentation, torsion representatives, or the coset-action test itself
# has an error -- do not proceed to Stage 2 interpretation until resolved.

########################################################################
# 9. STAGE 1 CONTROL: INDEX 6 CLASSIFICATION (volume ~5.333, NOT m009/m010)
########################################################################

Print("\n=== INDEX 6 CLASSIFICATION (control only -- wrong volume for m009/m010) ===\n");
results := [];
for H in idx6 do
    if IsTorsionFreeByCosetAction(T7, H, torsionReps) then
        Add(results, rec(
            index := 6,
            cusps := NumberOfCusps(T7, H, [p1, p2]),
            H1 := HomologyInvariants(H)
        ));
        Print("index=6  cusps=", results[Length(results)].cusps,
              "  H1=", results[Length(results)].H1, "\n");
    fi;
od;

Print("\nDone with Stage 1 (control run against ordinary T7).\n");

########################################################################
# STAGE 2: B7 = PGL_2(O_{-7}) -- candidate target for m009/m010
# (index 6 in B7, not in T7 -- see header comment for the full
# derivation and what is/isn't independently confirmed)
########################################################################

F_B7 := FreeGroup("A", "B", "U", "j");
A_B7 := F_B7.1;; B_B7 := F_B7.2;; U_B7 := F_B7.3;; j := F_B7.4;;

relsT7_forB7 := [
    B_B7^2,
    (B_B7*A_B7)^3,
    A_B7*U_B7*A_B7^-1*U_B7^-1,
    (B_B7*A_B7*U_B7^-1*B_B7*U_B7)^2
];

# J A J^-1 = A^-1, J B J^-1 = B^-1, J U J^-1 = U^-1 -- computed by hand
# from the real matrices above and independently checked numerically
# (exact agreement, zero error). Written as relators: j*g*j^-1*g = 1.
relsB7_ext := [
    j^2,
    j*A_B7*j^-1*A_B7,
    j*B_B7*j^-1*B_B7,
    j*U_B7*j^-1*U_B7
];

B7 := F_B7 / Concatenation(relsT7_forB7, relsB7_ext);
b7g := GeneratorsOfGroup(B7);
A_7 := b7g[1];; B_7 := b7g[2];; U_7 := b7g[3];; j_7 := b7g[4];;

Print("\nB7 presentation loaded (", Length(relsT7_forB7) + Length(relsB7_ext),
      " relators: T7's four + j^2 + three J-conjugation relators)\n");

p1_B7 := A_7;;  # T_1, same peripheral generators as T7 (B7 still has one cusp)
p2_B7 := U_7;;  # T_omega
torsionReps_B7 := [ B_7, B_7*A_7, j_7 ];  # includes the new involution j

idx6_B7 := Filtered(LowIndexSubgroupsFpGroup(B7, 6), H -> Index(B7, H) = 6);
Print("B7 index-6 classes: ", Length(idx6_B7), "\n");

Print("\n=== B7 INDEX 6 CLASSIFICATION (target: m009/m010) ===\n");
results_B7 := [];
for H in idx6_B7 do
    if IsTorsionFreeByCosetAction(B7, H, torsionReps_B7) then
        Add(results_B7, rec(
            index := 6,
            cusps := NumberOfCusps(B7, H, [p1_B7, p2_B7]),
            H1 := HomologyInvariants(H)
        ));
        Print("index=6  cusps=", results_B7[Length(results_B7)].cusps,
              "  H1=", results_B7[Length(results_B7)].H1, "\n");
    fi;
od;

# Target fingerprints (from gentry-galois-product-theorem.tex Prop. 3.2
# and the extensive Gamma^(2) trace-integrality check, this session):
#   m009: 1 cusp, H1 = Z (+) Z/2, peripheral lattice Z[sqrt(-7)]
#   m010: 1 cusp, H1 = Z (+) Z/6, peripheral lattice O_K
target009 := Filtered(results_B7, r -> r.cusps = 1 and r.H1 = [0, 2]);
target010 := Filtered(results_B7, r -> r.cusps = 1 and r.H1 = [0, 6]);

Print("\nOne-cusped index-6 classes with H1 = Z + Z/2 (m009 candidate): ",
      Length(target009), "\n");
Print("One-cusped index-6 classes with H1 = Z + Z/6 (m010 candidate): ",
      Length(target010), "\n");

# NOTE: matching H1 alone does not distinguish the peripheral lattice
# Z[sqrt(-7)] (m009) from O_K (m010) if both were to appear at H1=Z+Z/2
# and Z+Z/6 respectively by coincidence -- the peripheral-lattice check
# (index-2 sublattice test on the cusp translation subgroup) is the
# genuine falsifier and is not yet implemented here; treat a positive
# H1 match as a strong candidate, not a completed identification, until
# that additional check is added.
