#############################################################################
# bianchi_d7_lowindex.g
#
# PSL_2(O_{-7}) low-index subgroup experiment -- SKELETON, DO NOT RUN YET.
#
# REQUIRES: a verified d=-7 presentation copied directly from
# Grunewald & Schwermer, "Subgroups of Bianchi groups and arithmetic
# quotients of hyperbolic 3-space", Trans. Amer. Math. Soc. 335(1), 1993,
# pp. 47-78. Do not reconstruct the relators from memory or a relayed
# summary -- copy them from the source table.
#
# The companion presentation for the extended/maximal arithmetic overgroup
# (needed for Stage 2 below) is not yet sourced at all as of 2026-08-25.
#
# PURPOSE
# -------
# Stage 1 (control): enumerate index <= 6 subgroups of the ORDINARY
#   T7 = PSL_2(O_{-7}). Independently verified this session:
#     covol(T7) = 0.888914927816353  (Humbert volume formula, computed
#     directly via Sage/PARI, not taken from any relay)
#     vol(m009) = vol(m010) = 2.66674478344906
#     2.66674478344906 / 0.888914927816353 = 3.000000... exactly
#   Grunewald-Schwermer's torsion obstruction requires any torsion-free
#   finite-index subgroup of T7 to have index divisible by 6. Since the
#   volume ratio forces index 3 for a literal embedding, m009/m010 CANNOT
#   be subgroups of ordinary T7 -- this stage exists to confirm that
#   deduction computationally (all index-3 classes should show torsion)
#   and to see what index-6 torsion-free classes exist as a control, not
#   as a target (they'd have volume ~5.333, not ~2.667).
#
# Stage 2 (target, NOT YET RUNNABLE): repeat against the maximal discrete
#   arithmetic extension of T7, predicted covolume ~0.44445746 (i.e.
#   covol(T7)/2), which would put m009/m010 at index 6 in that extension.
#
# CANDIDATE for the Stage 2 group, status as of 2026-08-25:
#   B7 = PGL_2(O_{-7}), realized inside PSL_2(C) via determinant-rescaling
#   of representatives, generated by T7 plus one projective involution
#   J: z -> -z (a determinant -1 class), J^2 = 1.
#
#   What's independently confirmed (computed directly in Sage, not taken
#   from any relay):
#     class_number(Q(sqrt(-7))) = 1
#     unit_group(O_{-7}) = C2 (order 2, i.e. {+-1})
#     => O_K^x / (O_K^x)^2 = C2, so [PGL_2(O_K) : PSL_2(O_K)] = 2 is
#        elementary algebra, independent of any external source.
#     covol(B7) = covol(T7)/2 = 0.444457463908...  (follows immediately
#        from the index-2 fact above and the already-verified covol(T7))
#     2.666744783449.../0.444457463908... = 6.000000... exactly, so IF
#        m009/m010 embed in this group, the index-6 prediction is
#        internally consistent.
#
#   What is NOT independently confirmed: that PGL_2(O_{-7}) actually
#   equals Vulakh's B_d (his maximal discrete extension of PSL_2(O_d) in
#   PSL_2(C)) -- i.e. that PGL_2(O_{-7}) is truly MAXIMAL, not just A
#   discrete extension. The elementary index-2 argument above shows
#   PGL_2(O_K) is *a* valid discrete extension; it does not by itself
#   prove nothing larger exists. Citation checked and real: L. Ya.
#   Vulakh, "Reflections in extended Bianchi groups," Math. Proc.
#   Cambridge Philos. Soc. 115(1), 1994, DOI 10.1017/S0305004100071887
#   (confirmed via Cambridge's own listing: real title, real author,
#   real journal/year -- but the fetched abstract describes reflection/
#   Coxeter subgroups and Vinberg's class-number-divides-4 criterion,
#   not a verbatim "B_d = PGL_2(O_d)" statement; the paper's full text
#   was not read, so the maximality claim itself is plausible/consistent
#   with standard theory, not confirmed against Vulakh's actual theorem).
#
#   Explicit 2x2 matrix generators and relators for either T7 or B7 have
#   NOT been sourced. Two candidate sources for T7, both checked to be
#   real and correctly attributed (an earlier relay's "Dinakaran (2022)"
#   attribution is confirmed FALSE -- no such paper exists):
#     - Grunewald & Schwermer, Trans. Amer. Math. Soc. 335(1), 1993,
#       pp. 47-78 (see header above)
#     - Tanner Reese, "Presentations for singly-cusped Bianchi groups,"
#       arXiv:2206.01262 (2022) AND the published version, Topology
#       Appl. 328 (2023), article 108443, DOI 10.1016/j.topol.2023.108443
#       -- confirmed via Crossref metadata, real, both attributed solely
#       to Tanner Reese. Covers PSL_2(O_d) for d=-7 explicitly, per its
#       own abstract -- but is about the ORDINARY group, not the
#       extended/PGL_2 group, so it is a candidate source for T7's
#       presentation only, not a ready-made Stage 2 presentation.
#   Neither paper's full text has been read (no institutional access;
#   piracy routes are not something this project will use). Do not fill
#   in the generator/relator TODOs below by guessing.
#
#############################################################################

SetInfoLevel(InfoWarning, 1);

########################################################################
# 1. PRESENTATION -- NOT YET FILLED IN
########################################################################

# TODO: replace this stub with the verified d=-7 generators from
# Grunewald-Schwermer Table (Trans. AMS 335(1), 1993, pp. 47-78).
# The script intentionally errors out below rather than guessing.

F := FreeGroup("A", "B", "U");  # placeholder names only -- verify against source
gens := GeneratorsOfGroup(F);
A := gens[1];; B := gens[2];; U := gens[3];;

rels := [
    # TODO -- SOURCE-VERIFIED RELATOR 1 (Grunewald-Schwermer, d=-7 row)
    # TODO -- SOURCE-VERIFIED RELATOR 2
    # TODO -- ... copy every relator in that row, do not omit any
];

if Length(rels) = 0 then
    Print("FATAL: no verified relators entered. This script is a skeleton ",
          "and must not be run against a guessed presentation. See the ",
          "header comment for the required source.\n");
    QUIT_GAP(1);
fi;

T7 := F / rels;
tg := GeneratorsOfGroup(T7);

Print("T7 presentation loaded (", Length(rels), " relators)\n");

########################################################################
# 2. PERIPHERAL SUBGROUP -- NOT YET FILLED IN
########################################################################

# TODO: source-verified words in A,B,U giving the two generators of the
# cusp stabilizer P_infinity = Z^2 (translations by 1 and (1+sqrt(-7))/2).
# Needed for the cusp-count computation in section 6.

p1 := fail;;  # TODO
p2 := fail;;  # TODO

if p1 = fail or p2 = fail then
    Print("FATAL: peripheral generators not entered. Cusp counts in ",
          "section 6 will be meaningless without them.\n");
    QUIT_GAP(1);
fi;

########################################################################
# 3. TORSION REPRESENTATIVES -- NOT YET FILLED IN
########################################################################

# TODO: one representative word per relevant conjugacy class of maximal
# finite cyclic subgroup / elliptic element in T7, sourced from
# Grunewald-Schwermer. Do not assume only order-2/order-3 elements exist
# without checking the source table.

torsionReps := [
    # TODO -- SOURCE-VERIFIED elliptic representative(s)
];

if Length(torsionReps) = 0 then
    Print("FATAL: no torsion representatives entered. The index-3 control ",
          "check in section 8 cannot run without them.\n");
    QUIT_GAP(1);
fi;

########################################################################
# 4. LOW-INDEX ENUMERATION
########################################################################

lis := LowIndexSubgroupsFpGroup(T7, 6);
Print("Number of conjugacy classes index <= 6: ", Length(lis), "\n");

idx3 := Filtered(lis, H -> Index(T7, H) = 3);
idx6 := Filtered(lis, H -> Index(T7, H) = 6);
Print("Index 3 classes: ", Length(idx3), "\n");
Print("Index 6 classes: ", Length(idx6), "\n");

########################################################################
# 5. COSET-ACTION TORSION TEST
#
# Deliberately uses the coset action rather than a generic
# IsTorsionFree(H) call, which is not reliable for an arbitrary
# finite-index subgroup of an infinite finitely presented group: t is
# conjugate into H iff its permutation on H\G has a fixed point.
########################################################################

IsTorsionFreeByCosetAction := function(G, H, tors)
    local cosets, act, t, pt;
    cosets := RightCosets(G, H);
    act := ActionHomomorphism(G, cosets, OnRight);
    for t in tors do
        for pt in [1 .. Length(cosets)] do
            if pt ^ Image(act, t) = pt then
                return false;
            fi;
        od;
    od;
    return true;
end;

########################################################################
# 6. CUSP COUNT FROM DOUBLE COSETS H\G/P
#
# #{cusps of H} = |H\G/P|; P-orbits on H\G give exactly the double
# cosets, more rigorous here than inferring cusp count from H_1.
########################################################################

NumberOfCusps := function(G, H, periphGens)
    local cosets, act, Pperm, orbs;
    cosets := RightCosets(G, H);
    act := ActionHomomorphism(G, cosets, OnRight);
    Pperm := Group(List(periphGens, g -> Image(act, g)));
    orbs := Orbits(Pperm, [1 .. Length(cosets)]);
    return Length(orbs);
end;

########################################################################
# 7. ABELIANIZATION
########################################################################

HomologyInvariants := function(H)
    local iso, HFp;
    iso := IsomorphismFpGroup(H);
    HFp := Image(iso);
    return AbelianInvariants(HFp);  # GAP: 0 marks an infinite cyclic factor
end;

########################################################################
# 8. STAGE 1 CONTROL: INDEX 3 -- expect torsion-free = false, every time
########################################################################

Print("\n=== INDEX 3 CONTROL (expect torsion-free=false for all) ===\n");
for H in idx3 do
    Print("index=3  torsion-free=", IsTorsionFreeByCosetAction(T7, H, torsionReps), "\n");
od;
# If GAP reports any index-3 class as torsion-free: STOP. That means the
# presentation, torsion representatives, or the coset-action test itself
# has an error -- do not proceed to Stage 2 interpretation until resolved.

########################################################################
# 9. STAGE 1 CONTROL: INDEX 6 CLASSIFICATION (volume ~5.333, NOT m009/m010)
########################################################################

Print("\n=== INDEX 6 CLASSIFICATION (control only -- wrong volume for m009/m010) ===\n");
results := [];
for H in idx6 do
    if IsTorsionFreeByCosetAction(T7, H, torsionReps) then
        Add(results, rec(
            index := 6,
            cusps := NumberOfCusps(T7, H, [p1, p2]),
            H1 := HomologyInvariants(H)
        ));
        Print("index=6  cusps=", results[Length(results)].cusps,
              "  H1=", results[Length(results)].H1, "\n");
    fi;
od;

Print("\nDone with Stage 1 (control run against ordinary T7).\n");
Print("Stage 2 (the actual m009/m010 target search) requires source-verified\n");
Print("generator matrices -- see the skeleton and blocking condition below.\n");

########################################################################
# STAGE 2: B7 = PGL_2(O_{-7}) -- candidate target for m009/m010
# (index 6 in B7, not in T7 -- see header comment for the full
# derivation and what is/isn't independently confirmed)
#
# BLOCKING CONDITION: cannot run until (a) T7's generators are realized
# as explicit 2x2 matrices (from Grunewald-Schwermer or Reese, full text
# not yet accessed by this project) and (b) J*A*J^-1, J*B*J^-1, J*U*J^-1
# are computed from those matrices and rewritten as words in T7's own
# presentation. Nothing below this point should be run with guessed
# generators/relators/conjugation words.
########################################################################

F_B7 := FreeGroup("A", "B", "U", "j");
A_B7 := F_B7.1;; B_B7 := F_B7.2;; U_B7 := F_B7.3;; j := F_B7.4;;

relsT7_forB7 := [
    # TODO -- identical to section 1's relsT7 above, source-verified,
    # not duplicated by guesswork
];

# J: z -> -z is a determinant -1 projective involution; conjugating each
# T7 generator by J gives some word Phi(g) in T7's own generators. These
# words must be COMPUTED from the actual matrices, not guessed.
relsB7_ext := [
    j^2,
    # j*A_B7*j^-1 * PhiA^-1,   -- TODO: PhiA computed from J*Mat(A)*J^-1
    # j*B_B7*j^-1 * PhiB^-1,   -- TODO: PhiB computed from J*Mat(B)*J^-1
    # j*U_B7*j^-1 * PhiU^-1,   -- TODO: PhiU computed from J*Mat(U)*J^-1
];

if Length(relsT7_forB7) = 0 or Length(relsB7_ext) <= 1 then
    Print("\nFATAL: Stage 2 relators not entered (T7 relators and/or the\n");
    Print("J-conjugation words). This section is a skeleton and must not\n");
    Print("run against guessed input. See the header comment.\n");
    QUIT_GAP(1);
fi;

B7 := F_B7 / Concatenation(relsT7_forB7, relsB7_ext);

idx6_B7 := Filtered(LowIndexSubgroupsFpGroup(B7, 6), H -> Index(B7, H) = 6);
Print("\nB7 index-6 classes: ", Length(idx6_B7), "\n");

# Target fingerprints (from gentry-galois-product-theorem.tex Prop. 3.2
# and the extensive Gamma^(2) trace-integrality check, this session):
#   m009: 1 cusp, H1 = Z (+) Z/2, peripheral lattice Z[sqrt(-7)]
#   m010: 1 cusp, H1 = Z (+) Z/6, peripheral lattice O_K
# Apply the same IsTorsionFreeByCosetAction / NumberOfCusps /
# HomologyInvariants pipeline as Stage 1, against B7 and its own
# peripheral generators (also not yet sourced), once relsT7_forB7 and
# relsB7_ext are filled in.
