# Independent check of two claims in the relayed "final theorem" message:
# (1) [N_K(R):Gamma_009] = [N_K^+(R):Gamma_009^+] = 4 -- NOT just a
#     relabeling; needs [N_K(R):N_K^+(R)]=2 (automatic: N_K(R) acts on
#     the 2-element set {M0,M1}, and a nontrivial-acting subgroup of
#     Sym(2-set) has its "+" stabilizer at index exactly 2 -- this
#     nontriviality was already established: Gamma_009 itself contains
#     branch-swapping elements) plus [Gamma_009:Gamma_009^+]=2 (already
#     established), combined with [N_K^+(R):Gamma_009^+]=4 via clean
#     index multiplicativity along two subgroup chains -- derived here,
#     not just asserted.
# (2) Is Gamma_009^+ actually NORMAL in N_K^+(R) (so that "N_K(R)/Gamma_009"
#     is a literal group, not just a coset space), and if so, is the
#     quotient C2xC2 or C4? Checked directly in GAP using Codex's own
#     already-certified Iwahori/GammaPlus objects (reused, not rebuilt).

load("reproduce/m009_square_stabilizer_certificate.sage")

from sage.all import libgap

print()
print("=" * 72)
print("CLAIM (1): full index equals the endpoint-preserving index, DERIVED")
print("=" * 72)
print("""
Index multiplicativity along two chains from Gamma_009^+ to N_K(R):

  Gamma_009^+ subset Gamma_009 subset N_K(R)
  Gamma_009^+ subset N_K^+(R) subset N_K(R)

[N_K(R):Gamma_009^+] = [N_K(R):Gamma_009] * [Gamma_009:Gamma_009^+]
                      = [N_K(R):Gamma_009] * 2      (already certified)

[N_K(R):Gamma_009^+] = [N_K(R):N_K^+(R)] * [N_K^+(R):Gamma_009^+]
                      = [N_K(R):N_K^+(R)] * 4       (already certified)

[N_K(R):N_K^+(R)] = 2 exactly: N_K(R) acts on the 2-element set {M0,M1}
via conjugation; this action is NOT trivial (Gamma_009 itself already
contains branch-swapping elements, e.g. a itself, eps(a)=1 -- certified
this session), so the individual-point stabilizer N_K^+(R) has index
EXACTLY 2 in N_K(R) (index 1 or 2 for any action on a 2-set; nontrivial
action forces 2). Substituting:

  [N_K(R):Gamma_009] * 2 = 2 * 4 = 8
  [N_K(R):Gamma_009] = 4
""")
print("CONFIRMED: [N_K(R):Gamma_009] = 4 follows by clean index")
print("multiplicativity -- not a bare relabeling of the '+' result, but")
print("the same numeric value, for a real (if easy) reason.")

print()
print("=" * 72)
print("CLAIM (2): is Gamma_009^+ normal in N^{+,0} (=Iwahori-conjugate)?")
print("If so, what is the quotient group structure?")
print("=" * 72)

# Iwahori and GammaPlus are already built by the loaded script.
is_normal = bool(libgap.IsNormal(Iwahori, GammaPlus))
print("Gamma_009^+ normal in N^{+,0} (=Iwahori conjugate) =", is_normal)

if is_normal:
    Q = libgap.FactorGroup(Iwahori, GammaPlus)
    print("Quotient N^{+,0}/Gamma_009^+ structure:", libgap.StructureDescription(Q))
else:
    print("NOT normal -- 'N^{+,0}/Gamma_009^+' is not a group quotient;")
    print("only a coset SPACE of size 2 (already established/exhibited),")
    print("not a C2 factor to combine into C2xC2 or C4 as literally asked.")
    print("The C2xC2-vs-C4 question as posed needs re-examining: check")
    print("instead whether Gamma_009 (not just Gamma_009^+) is normal in")
    print("the FULL N_K(R), which is the actually well-posed version.")

# Also directly test the specific abstract question as posed: does the
# group generated by a representative of the branch-swap coset (already
# established: Gamma_009 itself contains one, e.g. 'a') together with Y
# (the certified nontrivial square-part coset representative) form
# C2xC2 or C4, WITHIN the ambient ...
print()
print("Also: within Gamma_009^+'s own index-2 ambient (Iwahori), the")
print("coset structure exhibited by the hardening certificate is")
print("{Gamma_009^+, y*Gamma_009^+} -- a coset SPACE of size 2, matching")
print("the already-certified [N^{+,0}:Gamma_009^+]=2, independent of")
print("whether it happens to be normal.")
