"""
m003_J3_strengthening_certificate.py
=====================================
Checks a proposed strengthening of Theorem 5.7 of the m003 paper: that the
collision ideal stabilizes at word length 3, not 5 -- i.e. J_infty = J_3,
not merely J_infty = J_5.

The claim rests on two facts, both independently verified elsewhere this
session and re-confirmed here from scratch:
  Delta_{aa,baa}   = h   exactly (not (y+1)h or (y^2+y-1)h)
  Delta_{AB,ABB}   = -q  exactly (already eq. (26) of the paper)

Both pairs consist of words of length <= 3. The logical chain, using only
facts already proved in Theorem 5.7 (not re-derived here):
  - K := P0 cap I(N) = <h, q>                          [already proved]
  - J_L subseteq K for every L (the "upper bound" half of Thm 5.7's proof
    is unconditional in the word-length cutoff: every generator Delta_{w,v}
    of J_L lies in P0, and by Prop 5.6 in I(N), for words of ANY length)
                                                          [already proved]
  - h, q are each literally Delta_{w,v} for a pair of words of length <=3
    satisfying Phi(tau_w)=Phi(tau_v)  (equivalently Delta_{w,v} in P0)
                                                          [checked below]
  => <h,q> = K subseteq J_3 subseteq J_infty subseteq K  (chain closes)
  => J_infty = J_3 = J_4 = J_5 = K = <h,q>

This script verifies every non-trivial ingredient exactly (sympy, no
floating point): the two trace differences, their exact equality to h and
-q (not merely membership), that aa/baa and AB/ABB do satisfy the
defining collision condition Delta in P0, and the resulting ideal
equality <h,q> = <Delta_{aa,baa}, Delta_{AB,ABB}> by Groebner comparison.

Exit status: 0 iff every assertion holds.
"""
import sys

import sympy as sp

x, y, z, u = sp.symbols("x y z u")
A = sp.Matrix([[x, -1], [1, 0]])
B = sp.Matrix([[0, -u], [-z - u, y]])
MAT = {"a": A, "A": sp.Matrix([[A[1, 1], -A[0, 1]], [-A[1, 0], A[0, 0]]]),
       "b": B, "B": sp.Matrix([[B[1, 1], -B[0, 1]], [-B[1, 0], B[0, 0]]])}
DET = u**2 + z * u + 1


def tr_xyz(word):
    M = sp.eye(2)
    for c in word:
        M = M * MAT[c]
    tr = sp.expand(M.trace())
    return sp.expand(sp.rem(tr, DET, u))


ok = True


def check(label, cond):
    global ok
    print(("PASS  " if cond else "FAIL  ") + label)
    ok &= bool(cond)


h = x**2 - x * z + y - 2
q = y * z - x - z
P0 = [x * z + 1, x**2 + y - 1]
GP0 = sp.groebner(P0, x, y, z, order="grevlex")


def in_P0(p):
    return sp.expand(sp.reduced(sp.expand(p), list(GP0.exprs), x, y, z, order="grevlex")[1]) == 0


D_aa_baa = sp.expand(tr_xyz("aa") - tr_xyz("baa"))
D_AB_ABB = sp.expand(tr_xyz("AB") - tr_xyz("ABB"))

print("Delta_{aa,baa} =", D_aa_baa, "  (lengths 2,3)")
print("Delta_{AB,ABB} =", D_AB_ABB, "  (lengths 2,3)")
check("Delta_{aa,baa} == h exactly (coefficient 1, not (y+1) or (y^2+y-1))",
      sp.expand(D_aa_baa - h) == 0)
check("Delta_{AB,ABB} == -q exactly", sp.expand(D_AB_ABB + q) == 0)

check("Delta_{aa,baa} in P0  (=> Phi(tau_aa)=Phi(tau_baa), a legitimate J_3 generator)",
      in_P0(D_aa_baa))
check("Delta_{AB,ABB} in P0  (=> Phi(tau_AB)=Phi(tau_ABB), a legitimate J_3 generator)",
      in_P0(D_AB_ABB))

K = sp.groebner([h, q], x, y, z, order="grevlex")
J3_witnesses = sp.groebner([D_aa_baa, D_AB_ABB], x, y, z, order="grevlex")
check("<Delta_{aa,baa}, Delta_{AB,ABB}> == <h,q> == K  (Groebner bases coincide)",
      list(K.exprs) == list(J3_witnesses.exprs))

print()
if ok:
    print("CONCLUSION: K = P0 cap I(N) = <h,q> is generated by two trace")
    print("            differences of words of length <= 3 (aa/baa, AB/ABB),")
    print("            both independently confirmed to satisfy the defining")
    print("            collision condition. Combined with the already-proved")
    print("            J_L subseteq K for every L (Theorem 5.7's upper bound,")
    print("            unconditional in L) and K subseteq J_3 (from these two")
    print("            witnesses), the chain K subseteq J_3 subseteq J_infty")
    print("            subseteq K closes, giving")
    print()
    print("            J_infty = J_3 = J_4 = J_5 = P0 cap I(N) = <h,q>.")
    print()
    print("            This STRENGTHENS Theorem 5.7 as published (which states")
    print("            J_infty=J_5): the same ideal is already generated by")
    print("            collisions of word length <= 3, not merely <= 5. The")
    print("            statement J_infty=J_5 remains true; J_infty=J_3 is a")
    print("            strictly stronger, equally exact fact.")
else:
    print("CONCLUSION: NOT ESTABLISHED -- see failures above.")
sys.exit(0 if ok else 1)
