"""
Theorem-level question raised after the m006 collision-certificate work:
does the bounded-word-length (<=6) atlas's word-trace collision
structure recover the FULL exact defining ideal of X_0, for either
manifold?

Answer, established here exactly for BOTH m003 and m006: NO -- but not
by a little, and not in an ad hoc way. In both cases the ideal
generated by every genuinely component-specific atlas collision
difference equals

    J_atlas = I(X_0) ∩ I(N),   N = V(x-z, y-2)

for the SAME universal line N, independent of the manifold. This is a
proper sub-ideal of I(X_0) in both cases (J_atlas != I(X_0)), directly
analogous to Stage 4's ambient-decomposition finding for m003's
original 3-identity ideal J_D = I(X_0) ∩ I(L) ∩ I(M) (with
M = V(y-2,x-z) -- literally the same line as N here), but now shown to
hold for the FULL atlas-derived ideal (all genuine collisions, not
just the 3 originally-known identities) and for m006 too.

Interpretation (flagged as a lead, not proved here): N requires
y = tr(b) = 2, which forces the Fricke matrix B to be parabolic
(trace 2, repeated eigenvalue 1) -- a degenerate locus where matrix
powers behave specially (B^n = I + n(B-I) for unipotent B), plausibly
producing extra generic word-trace coincidences independent of either
manifold's specific relator. Not yet verified as a general phenomenon
beyond these two manifolds.

Reuses the certified Fricke/Phi infrastructure from
m003_stage4_x0_identity_origin.py and m006_x0_identity_origin.py.
"""

import csv
import sys
from collections import defaultdict

import sympy as sp

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

x, y, z, u, t, w = sp.symbols("x y z u t w")

A = sp.Matrix([[x, -1], [1, 0]])
uinv = -z - u
B = sp.Matrix([[0, -u], [uinv, y]])
I2 = sp.eye(2)


def inv_sl2(M):
    return sp.Matrix([[M[1, 1], -M[0, 1]], [-M[1, 0], M[0, 0]]])


MATS = {"a": A, "A": inv_sl2(A), "b": B, "B": inv_sl2(B)}
DET_REL = sp.Poly(u**2 + z * u + 1, u)


def word_matrix(word):
    M = I2
    for c in word:
        M = M * MATS[c]
    return sp.expand(M)


def tr_xyz(word):
    tr = sp.expand(word_matrix(word).trace())
    _, r = sp.div(sp.Poly(tr, u), DET_REL, u)
    r = sp.expand(r.as_expr())
    assert sp.Poly(r, u).degree() <= 0, f"{word}: residual u term {r}"
    return sp.expand(r)


def banner(s):
    print("\n" + "=" * 78 + "\n" + s + "\n" + "=" * 78)


def ideal_intersect(gensA, gensB):
    combined = [w * gg for gg in gensA] + [(1 - w) * gg for gg in gensB]
    G = sp.groebner(combined, w, x, y, z, order="lex")
    return [p for p in G.exprs if w not in p.free_symbols]


words_meta = {}
with open("m003_word_atlas.csv") as f:
    for row in csv.DictReader(f):
        if row["filling"] == "m003(cusp)":
            words_meta[row["word"]] = True
assert len(words_meta) == 99
trxyz = {wd: tr_xyz(wd) for wd in words_meta}


def atlas_ideal(param):
    """Genuine (non-ambient) collision differences under `param`, as an ideal."""
    by_poly = defaultdict(list)
    for wd, p in trxyz.items():
        val = sp.cancel(sp.together(p.subs(param)))
        by_poly[sp.srepr(val)].append(wd)
    groups = [sorted(v) for v in by_poly.values() if len(v) > 1]
    deltas = set()
    for grp in groups:
        w0 = grp[0]
        for wi in grp[1:]:
            d = sp.expand(trxyz[w0] - trxyz[wi])
            if d != 0:
                deltas.add(d)
    return len(groups), deltas


N_gens = [x - z, y - 2]   # the universal spurious line

# ==========================================================================
banner("m003:  J_atlas(m003) vs I(X_0(m003)) and N = V(x-z,y-2)")

PARAM_M003 = {x: t, y: 1 - t**2, z: -1 / t}
ngroups3, deltas3 = atlas_ideal(PARAM_M003)
print(f"  {ngroups3} collision groups, {len(deltas3)} distinct nonzero Deltas")

IX0_m003 = [x * z + 1, x**2 + y - 1]
G_IX0_003 = sp.groebner(IX0_m003, x, y, z, order="grevlex")
G_J003 = sp.groebner(list(deltas3), x, y, z, order="grevlex")
print(f"  I(X_0(m003)) Groebner basis: {list(G_IX0_003.exprs)}")
print(f"  J_atlas(m003) Groebner basis: {list(G_J003.exprs)}")
print(f"  J_atlas(m003) == I(X_0(m003)): "
      f"{set(G_J003.exprs) == set(G_IX0_003.exprs)}")

K3 = ideal_intersect(N_gens, IX0_m003)
G_K3 = sp.groebner(K3, x, y, z, order="grevlex")
print(f"  N ∩ I(X_0(m003)) Groebner basis: {list(G_K3.exprs)}")
print(f"  J_atlas(m003) == N ∩ I(X_0(m003)): "
      f"{set(G_J003.exprs) == set(G_K3.exprs)}")

# ==========================================================================
banner("m006:  J_atlas(m006) vs I(X_0(m006)) and the SAME N = V(x-z,y-2)")

PARAM_M006 = {x: t, y: 1 / (t**2 - 1), z: t}
ngroups6, deltas6 = atlas_ideal(PARAM_M006)
print(f"  {ngroups6} collision groups, {len(deltas6)} distinct nonzero Deltas")

IX0_m006 = [x - z, y * (z**2 - 1) - 1]
G_IX0_006 = sp.groebner(IX0_m006, x, y, z, order="grevlex")
G_J006 = sp.groebner(list(deltas6), x, y, z, order="grevlex")
print(f"  I(X_0(m006)) Groebner basis: {list(G_IX0_006.exprs)}")
print(f"  J_atlas(m006) Groebner basis: {list(G_J006.exprs)}")
print(f"  J_atlas(m006) == I(X_0(m006)): "
      f"{set(G_J006.exprs) == set(G_IX0_006.exprs)}")

K6 = ideal_intersect(N_gens, IX0_m006)
G_K6 = sp.groebner(K6, x, y, z, order="grevlex")
print(f"  N ∩ I(X_0(m006)) Groebner basis: {list(G_K6.exprs)}")
print(f"  J_atlas(m006) == N ∩ I(X_0(m006)): "
      f"{set(G_J006.exprs) == set(G_K6.exprs)}")

# explicit factorization showing the mechanism for m006 (parallel to m003's
# already-recorded D_2=-g1, D_1=(y+1)D_2 mechanism)
banner("m006 mechanism: the second generator of J_atlas factors as (y-2)*g1")
g2_006, g1_006 = IX0_m006
J_second_gen = [p for p in G_J006.exprs if p != g2_006 and (x - z) not in [p]]
for p in G_J006.exprs:
    print(f"  J_atlas(m006) generator: {p}   factored: {sp.factor(p)}")

banner("cross-manifold verdict")
print(f"  Both J_atlas(m003) and J_atlas(m006) equal I(X_0) ∩ I(N) for the")
print(f"  SAME line N = V(x-z, y-2) -- a proper sub-ideal of I(X_0) in both")
print(f"  cases. The bounded-length atlas does NOT quite recover the exact")
print(f"  component ideal from either manifold's collisions alone; it")
print(f"  recovers X_0 together with one universal spurious line, common to")
print(f"  both manifolds and identical to the spurious line M found in")
print(f"  m003's earlier (3-identity-only) ambient decomposition.")
print(f"  N requires y=tr(b)=2, forcing the Fricke matrix B to be parabolic")
print(f"  (trace 2, repeated eigenvalue 1) -- a plausible but NOT YET PROVED")
print(f"  source of generic, manifold-independent word-trace coincidences.")

print("\nPY_EXIT=0")
