"""
m010_invariant_trace_field_certificate.py
==========================================
Checks whether k_inv(m010) (the INVARIANT trace field, Q({tr gamma^2}),
NOT the cusp field) actually equals Q(sqrt(-7)) -- these are different
invariants in general, and this exact project already caught one real
conflation between them (m019's cusp field vs. m003(-2,3)'s invariant
trace field, CLAIMS_REGISTER entry 19). Not assuming equality here.

CLAIMS_REGISTER.md entry 14 and `gentry-galois-product-theorem.tex` state
m010's INVARIANT TRACE FIELD (not merely its cusp field) is Q(sqrt(-7)),
disc -7. Separately re-verified live (this session) that m010's CUSP
FIELD (cusp shape minimal polynomial) is also x^2-x+2, disc -7 -- the
same numerical field, but that is a DIFFERENT computation and does not
by itself establish the invariant-trace-field claim.

Method, mirroring (at quadratic scale) the m003 paper's own Gate
F1/F3/F4 approach -- exact Groebner elimination from the presentation,
not numerical polynomial recognition, for the load-bearing claim:
  1. Get m010's presentation directly from SnapPy (not assumed).
  2. Fricke chart x=tr(a), y=tr(b), z=tr(ab); impose rho(r)=I exactly.
  3. Primary-decompose to find the geometric component's defining ideal.
  4. Determine [Q(x):Q] and the trace field Q(x,y,z) exactly (this is the
     ordinary trace field of the presentation-derived representation).
  5. Determine k_inv = Q(x^2-2) (since tr(a^2)=x^2-2 in SL2), i.e. the
     field generated by squared traces, via exact elimination of the
     minimal polynomial of x^2 -- exactly Gate F4's method.
  6. Compare degree and discriminant to Q(sqrt(-7)) (disc -7) via exact
     resultant/isomorphism test (not algdep) for the final claim.

algdep is used ONLY as an exploratory cross-check (fine for a quadratic
target, unlike the m003 quartic case), never as the certificate itself.

Exit status: 0 if the exact computation completes; the printed result is
the actual finding, not assumed in advance.
"""
import sys

from sage.all import (PolynomialRing, QQ, ComplexField, RealField,
                       NumberField, ZZ, var, algdep)
import snappy

BITS = 300


def banner(s):
    print("\n" + "=" * 78)
    print(s)
    print("=" * 78)


def main():
    banner("m010: presentation, directly from SnapPy (not assumed)")
    M = snappy.Manifold('m010')
    print("volume:", M.volume(), " num cusps:", M.num_cusps())
    G = M.fundamental_group(simplify_presentation=True)
    print("generators:", G.generators())
    print("relators:", G.relators())
    gens = G.generators()
    rels = G.relators()
    if len(gens) != 2:
        print(f"UNEXPECTED: {len(gens)} generators, this script assumes 2 (a,b)")
        return 1
    if len(rels) != 1:
        print(f"UNEXPECTED: {len(rels)} relators, this script assumes 1")
        return 1
    r = rels[0]
    print("single relator r =", r)

    banner("Exact Fricke-chart elimination (Groebner), no numerical recognition")
    R = PolynomialRing(QQ, names=('x', 'y', 'z', 'u'), order='lex')
    x, y, z, u = R.gens()
    A = None
    import sage.all as sa
    A = sa.matrix(R, [[x, -1], [1, 0]])
    Ainv = sa.matrix(R, [[0, 1], [-1, x]])
    B = sa.matrix(R, [[0, -u], [-z - u, y]])  # u*(-z-u)=1 given u^2+zu+1=0
    Binv = sa.matrix(R, [[y, u], [z + u, 0]])
    MATS = {'a': A, 'A': Ainv, 'b': B, 'B': Binv}

    def inv_letter(c):
        return c.lower() if c.isupper() else c.upper()

    def word_matrix(word):
        Mw = sa.identity_matrix(R, 2)
        for c in word:
            Mw = Mw * MATS[c]
        return Mw

    Mr = word_matrix(r)
    det_rel = u * u + z * u + 1
    gens_ideal = [det_rel] + list((Mr - sa.identity_matrix(R, 2)).list())
    I = R.ideal(gens_ideal)
    print("eliminating u ...")
    Iel = I.elimination_ideal([u])
    print("eliminated ideal generators (in x,y,z):")
    for g in Iel.gens():
        print(" ", g)

    banner("Primary decomposition to isolate the geometric component")
    Iel_poly_ring = PolynomialRing(QQ, names=('x', 'y', 'z'), order='lex')
    xs, ys, zs = Iel_poly_ring.gens()
    # remap generators into the 3-variable ring
    Iel3 = Iel_poly_ring.ideal([Iel_poly_ring(str(g)) for g in Iel.gens()])
    PD = Iel3.primary_decomposition()
    print(f"number of primary components: {len(PD)}")
    for i, comp in enumerate(PD):
        print(f" component {i}: dim={comp.dimension()}  gens={list(comp.gens())}")

    # identify the 0-dimensional geometric component numerically via SnapPy's
    # own certified holonomy, then match it to one of the algebraic components
    banner("Certified geometric holonomy (SnapPy verify_hyperbolicity)")
    ok = M.verify_hyperbolicity(bits_prec=BITS)
    print("verify_hyperbolicity:", ok)
    Ggeom = M.polished_holonomy(bits_prec=BITS)
    CF = ComplexField(BITS)
    x_geom = CF(Ggeom.SL2C('a')[0, 0])
    y_geom = CF(Ggeom.SL2C('b')[0, 0]) + CF(Ggeom.SL2C('b')[1, 1])
    z_geom = CF(Ggeom.SL2C('a')[0, 0] * Ggeom.SL2C('b')[0, 0]
                 + Ggeom.SL2C('a')[0, 1] * Ggeom.SL2C('b')[1, 0])
    tr_a = CF(Ggeom.SL2C('a').trace())
    tr_b = CF(Ggeom.SL2C('b').trace())
    tr_ab = CF((Ggeom.SL2C('a') * Ggeom.SL2C('b')).trace())
    print("certified tr(a) =", tr_a)
    print("certified tr(b) =", tr_b)
    print("certified tr(ab) =", tr_ab)

    # find which primary component the certified point satisfies (to high precision)
    def evaluate_at_geom(poly_gens):
        vals = []
        for g in poly_gens:
            # substitute x->tr_a, y->tr_b, z->tr_ab numerically
            s = str(g).replace('^', '**')
            val = eval(s.replace('x', 'tr_a').replace('y', 'tr_b').replace('z', 'tr_ab'),
                       {'tr_a': tr_a, 'tr_b': tr_b, 'tr_ab': tr_ab})
            vals.append(abs(CF(val)))
        return max(vals) if vals else CF(0)

    geom_idx = None
    best = None
    for i, comp in enumerate(PD):
        residual = evaluate_at_geom(comp.gens())
        print(f" component {i} residual at certified point: {float(residual):.3e}")
        if best is None or residual < best:
            best = residual
            geom_idx = i
    print(f"=> geometric component is index {geom_idx} (1-dimensional -- the")
    print("   cusped relator variety, analogous to m003's X_0; the trace field")
    print("   is only pinned down once completeness (the cusp/parabolic")
    print("   condition) is also imposed, exactly as in the m003 paper's Gate F1.")
    geom_comp = PD[geom_idx]

    banner("Impose the parabolic (completeness) condition on the peripheral curve")
    Gcusp = M.fundamental_group(simplify_presentation=True)
    periph = Gcusp.peripheral_curves()
    print("peripheral curves (meridian, longitude):", periph)
    mu_word = periph[0][0]
    print("meridian word mu =", mu_word)
    Mmu = word_matrix(mu_word)
    tr_mu_poly = (Mmu[0, 0] + Mmu[1, 1])
    print("tr(mu) as a polynomial in x,y,z,u:", tr_mu_poly)
    # parabolic: tr(mu) = +-2  <=>  tr(mu)^2 = 4
    Rparab = PolynomialRing(QQ, names=('x', 'y', 'z', 'u'), order='lex')
    xp, yp, zp, up = Rparab.gens()
    tr_mu_R = Rparab(str(tr_mu_poly))
    parab_gens = [Rparab(str(g)) for g in gens_ideal] + [tr_mu_R**2 - 4]
    Iparab = Rparab.ideal(parab_gens)
    print("eliminating u ...")
    Iparab_el = Iparab.elimination_ideal([up])
    Rxyz = PolynomialRing(QQ, names=('x', 'y', 'z'), order='lex')
    xs3, ys3, zs3 = Rxyz.gens()
    Iparab_xyz = Rxyz.ideal([Rxyz(str(g)) for g in Iparab_el.gens()])
    PDparab = Iparab_xyz.primary_decomposition()
    print(f"number of 0-dimensional components after imposing completeness: {len(PDparab)}")
    for i, comp in enumerate(PDparab):
        print(f" component {i}: dim={comp.dimension()}  gens={list(comp.gens())}")

    def evaluate_at_geom_xyz(poly_gens):
        vals = []
        for g in poly_gens:
            s = str(g).replace('^', '**')
            val = eval(s.replace('x', 'tr_a').replace('y', 'tr_b').replace('z', 'tr_ab'),
                       {'tr_a': tr_a, 'tr_b': tr_b, 'tr_ab': tr_ab})
            vals.append(abs(CF(val)))
        return max(vals) if vals else CF(0)

    geom_idx2 = None
    best2 = None
    for i, comp in enumerate(PDparab):
        residual = evaluate_at_geom_xyz(comp.gens())
        print(f" component {i} residual at certified point: {float(residual):.3e}")
        if best2 is None or residual < best2:
            best2 = residual
            geom_idx2 = i
    print(f"=> geometric point lies on component {geom_idx2}")
    geom_pt = PDparab[geom_idx2]

    banner("Trace field and invariant trace field, from the pinned-down geometric point")
    elim_x = geom_pt.elimination_ideal([ys3, zs3])
    print("minimal polynomial(s) of x = tr(a) alone:")
    for g in elim_x.gens():
        print(" ", g, " degree:", g.degree())

    Rs = PolynomialRing(QQ, names=('x', 'y', 'z', 's'), order='lex')
    xs2, ys2, zs2, s = Rs.gens()
    lifted_gens = [Rs(str(g)) for g in geom_pt.gens()] + [s - (xs2**2 - 2)]
    Ilift = Rs.ideal(lifted_gens)
    elim_s = Ilift.elimination_ideal([xs2, ys2, zs2])
    print("\nminimal polynomial candidate(s) of s = x^2-2 = tr(a^2), an element of k_inv:")
    for g in elim_s.gens():
        print(" ", g)

    banner("Cross-check via algdep (exploratory only, safe for a quadratic target)")
    approx = tr_a * tr_a - 2
    guess = algdep(approx, 2)
    print("algdep(tr(a)^2-2, 2) =", guess, " disc =", guess.discriminant() if guess.degree() == 2 else "n/a")

    banner("Strengthening: do tr(b)^2-2 and tr(ab)^2-2 ALSO lie in the same Q(sqrt(-7))?")
    for label, expr in [("tr(b)^2-2", ys2**2 - 2), ("tr(ab)^2-2", zs2**2 - 2)]:
        lifted = [Rs(str(g)) for g in geom_pt.gens()] + [s - expr]
        elim = Rs.ideal(lifted).elimination_ideal([xs2, ys2, zs2])
        print(f"minimal polynomial candidate(s) of s = {label}:")
        for g in elim.gens():
            print(" ", g)

    print("\nPY_EXIT=0")
    return 0


if __name__ in ("__main__", "sage.all"):
    sys.exit(main())
