# PMNS invariant trace field: gates F3+F4 (reduced algebra), completing
# the CKM-style four-gate closure begun in pmns_itf_certificate.sage
# (which established F1: presentation-only elimination, and F2: certified
# geometric root -- both re-derived here too, for a single self-contained
# certificate).
#
# m003(-2,3) turns out to be CLEANER than CKM's m006(-5,2): the filled
# coordinate ring R/I_filled is already reduced and prime -- dim_Q = 4,
# matching [K283:Q] exactly, with no nilpotent "thickening" (CKM needed
# u=z-x, u^2=0 to strip out; here there is nothing to strip). So gates
# F3/F4 are the direct Fricke-trace-algebra argument, not a localization.

from sage.all import *

R = PolynomialRing(QQ, names=("x", "y", "z", "u"), order="degrevlex")
x, y, z, u = R.gens()

A = matrix(R, [[x, -1], [1, 0]])
uinv = -z - u
B = matrix(R, [[0, -u], [uinv, y]])
I2 = identity_matrix(R, 2)


def inv_sl2(M):
    return matrix(R, [[M[1, 1], -M[0, 1]], [-M[1, 0], M[0, 0]]])


Ai = inv_sl2(A)
Bi = inv_sl2(B)
MATS = {"a": A, "A": Ai, "b": B, "B": Bi}


def word_matrix(word):
    M = I2
    for c in word:
        M = M * MATS[c]
    return M


def inverse_word(word):
    swap = {"a": "A", "A": "a", "b": "B", "B": "b"}
    return "".join(swap[c] for c in reversed(word))


def banner(t):
    print("\n" + "=" * 78)
    print(t)
    print("=" * 78)


det_relation = u**2 + z*u + 1

banner("m003 exact presentation (from SnapPy, verified this session)")
import snappy
Mcusp = snappy.Manifold("m003")
Gcusp = Mcusp.fundamental_group()
relator = str(Gcusp.relators()[0])
mu, longitude = (str(w) for w in Gcusp.peripheral_curves()[0])
print("relator =", relator, " mu =", mu, " longitude =", longitude)
assert relator == "abAAbabbb" and mu == "ABABB" and longitude == "ABAbab"

Mr = word_matrix(relator)
gens_riley = [det_relation] + list((Mr - I2).list())
filling_word = inverse_word(mu) * 2 + longitude * 3
Ms = word_matrix(filling_word)
gens_filled = gens_riley + list((Ms - I2).list())
I_filled = R.ideal(gens_filled)
Iel_filled = I_filled.elimination_ideal([u])
print("filled ideal generators (pure x,y,z):", list(Iel_filled.gens()))

banner("GATE F3/F4 SETUP: the reduced character algebra")
S3 = PolynomialRing(QQ, names=("x", "y", "z"))
sx, sy, sz = S3.gens()
phi = R.hom([sx, sy, sz, S3(0)], S3)
J3 = S3.ideal([phi(g) for g in Iel_filled.gens()])

dimQ = J3.vector_space_dimension()
is_radical = (J3 == J3.radical())
is_prime = J3.is_prime()
print("dim_Q(R/I_filled) =", dimQ)
print("R/I_filled is radical (no nilpotents)?", is_radical)
print("R/I_filled is prime (an integral domain)?", is_prime)
assert dimQ == 4
assert is_radical
assert is_prime
print()
print("A finite-dimensional integral domain over a field is automatically")
print("a field. So R/I_filled IS a number field of degree 4 -- no")
print("localization or nilpotent quotient needed (unlike CKM's B_red")
print("construction), since there is nothing here to quotient away.")

banner("GATE F3: upper inclusion k_inv(M_PMNS) subset K")
# Build K abstractly from the coordinate ring's own minimal polynomial in x.
Ux = PolynomialRing(QQ, "T")
Tg = Ux.gen()
# eliminate y,z from J3 to get x's exact minimal polynomial (same result as
# established directly from tr(a) earlier this session).
Slex = PolynomialRing(QQ, names=("y", "z", "x"), order="lex")
sy2, sz2, sx2 = Slex.gens()
phi2 = S3.hom([sx2, sy2, sz2], Slex)
Jlex = Slex.ideal([phi2(g) for g in J3.gens()])
GBlex = Jlex.groebner_basis()
to_Ux = Slex.hom([Ux(0), Ux(0), Tg], Ux)
univ_x = [to_Ux(g) for g in GBlex if g.degree(sy2) == 0 and g.degree(sz2) == 0]
assert len(univ_x) == 1
p_x = univ_x[0]
print("exact minimal polynomial of x=tr(a):", p_x)
assert p_x.is_irreducible()
assert p_x.degree() == 4

K = NumberField(p_x, "xi")
print("K = Q(x), [K:Q] =", K.degree(), " disc(K) =", K.discriminant())
print()
print("Since R/I_filled has dimension exactly [K:Q]=4 over Q and is a")
print("field, and x already generates a degree-4 subfield, R/I_filled")
print("= Q(x) = K exactly (equal Q-dimensions force equality).")
print()
print("For a two-generator SL2 representation, every word trace is a")
print("Fricke polynomial in x,y,z (standard fact, same argument used for")
print("CKM). At the geometric point, x,y,z all lie in the coordinate ring")
print("R/I_filled = K. Hence every trace, and so every SQUARED trace, lies")
print("in K:")
print()
print("   k_inv(M_PMNS) = Q(tr^2 rho(g) : g in pi_1) SUBSET K.")

banner("GATE F4: lower inclusion K subset k_inv(M_PMNS)")
xi = K.gen()
xsq = xi**2
mp_xsq = xsq.minpoly()
print("x^2 = tr^2(rho(a)) -- manifestly an element of k_inv(M_PMNS) by")
print("definition (k_inv is generated by exactly such squared traces).")
print("minimal polynomial of x^2 over Q:", mp_xsq)
assert mp_xsq.degree() == 4
print("[Q(x^2):Q] =", mp_xsq.degree(), "= [K:Q] = 4")
QQ_xsq_degree = mp_xsq.degree()
same_field = (QQ_xsq_degree == K.degree())
print("Q(x^2) subset Q(x)=K and both have Q-dimension 4, hence equal:",
      same_field)
assert same_field
print()
print("So Q(x^2) = Q(x) = K, and since x^2 in k_inv(M_PMNS):")
print()
print("   K = Q(x^2) SUBSET k_inv(M_PMNS).")

banner("GATE F1/F2 re-confirmation (already certified in")
print("pmns_itf_certificate.sage; re-derived here for a self-contained")
print("record)")
BITS_PREC = 300
FUNDAMENTAL_GROUP_ARGS = [True, False, True, False]
Mgeom = snappy.Manifold("m003(-2,3)")
ok, rho = Mgeom.verify_hyperbolicity(
    holonomy=True, bits_prec=BITS_PREC,
    fundamental_group_args=FUNDAMENTAL_GROUP_ARGS)
print("verify_hyperbolicity(holonomy=True, bits_prec=%d) =" % BITS_PREC, ok)
assert ok
Grho_relators = tuple(str(w) for w in rho.relators())
assert relator in Grho_relators, "rho's presentation does not contain the exact cusped relator"
T_a = rho("a").trace()
print("certified T_a = tr(rho('a')) =", T_a)

CIF = ComplexIntervalField(BITS_PREC)
RIF = RealIntervalField(BITS_PREC)
p_x_CIF = p_x.change_ring(CIF)
p_x_prime_CIF = p_x_CIF.derivative()
delta = RIF(2)**(-BITS_PREC + 20)
pad = RIF(-1, 1) * delta
box = CIF(T_a.real() + pad, T_a.imag() + pad)
mid = CIF((box.real().lower() + box.real().upper()) / 2,
          (box.imag().lower() + box.imag().upper()) / 2)
N_box = mid - p_x_CIF(mid) / p_x_prime_CIF(box)


def strictly_contained(inner, outer):
    return (inner.real().lower() > outer.real().lower()
            and inner.real().upper() < outer.real().upper()
            and inner.imag().lower() > outer.imag().lower()
            and inner.imag().upper() < outer.imag().upper())


contracted = strictly_contained(N_box, box)
print("interval-Newton contraction on p_x at the certified T_a box:",
      contracted)
assert contracted

banner("FULL FOUR-GATE CERTIFICATE SUMMARY")
print("Gate F1 (presentation-only elimination): PASS (pmns_itf_certificate.sage)")
print("Gate F2 (certified geometric root, interval-Newton): PASS (re-confirmed here)")
print("Gate F3 (upper inclusion, k_inv subset K): PASS")
print("  R/I_filled is reduced, prime, dim_Q=4 -- IS the field K, no")
print("  localization needed; every trace lies in it by Fricke algebra.")
print("Gate F4 (lower inclusion, K subset k_inv): PASS")
print("  x^2 in k_inv by definition; [Q(x^2):Q]=4=[K:Q] so Q(x^2)=K.")
print()
print("CONCLUSION:")
print()
print("   k_inv(m003(-2,3)) = K,  [K:Q] = 4,  disc(K) = %s" % K.discriminant())
print()
print("matching the historically-claimed K283 = Q[t]/(t^4+t^3-1) as an")
print("abstract field (disc -283, isomorphic -- established earlier this")
print("session), now proved by the complete CKM-style four-gate chain --")
print("no algdep, no PSLQ, no numerical polynomial recognition anywhere.")
print()
print("PMNS ITF FOUR-GATE CERTIFICATE: PASS")
print("SAGE_EXIT=0")
